source 'http://rubygems.org'

ruby '2.1.0'

gem 'i18n', github: 'svenfuchs/i18n'
gem 'rails', '~>4.1.0'

gem 'inherited_resources'
gem 'pg'
gem 'slim'
gem 'slim-rails'
gem 'httparty'
gem 'gmaps4rails'
gem 'devise'
gem 'devise-i18n'
gem 'rails-i18n', github: 'svenfuchs/rails-i18n', branch: 'master'
gem 'neat'
gem 'normalize-rails'
gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'
gem 'jquery-rails'
gem 'underscore-rails'
gem 'turbolinks'
gem 'jquery-turbolinks'
gem 'fb-channel-file'
gem 'nprogress-rails'
gem 'spring', group: :development
gem 'high_voltage'
gem 'rails_12factor', group: :production
